[package]
name = "orm"
version = "0.2.0"
edition = "2021"

[dependencies]
orm_macros = { path = "../orm_macros" }
sqlx = { version = "=0.9.0-alpha.1", default-features = false, features = ["postgres"] }
tokio = { version = "1", features = ["time"] }
